version: '3'
services:
  mysql-server:
    image: 99afc808f15b
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    #    volumes:
    #      - ./storage:/data
    volumes:
      - D:\minio-storage:/data
    environment:
      MINIO_ROOT_USER: khue1234
      MINIO_ROOT_PASSWORD: khue1234
    command: server --console-address ":9001" /data

