version: '3'
services:

  #mySql server
  mysql-server:
    image: 99afc808f15b
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
  #minio server
  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    #    volumes:
    #      - ./storage:/data
    volumes:
      - D:\minio-storage:/data
    environment:
      MINIO_ROOT_USER: khue1234
      MINIO_ROOT_PASSWORD: khue1234
    command: server --console-address ":9001" /data

  #server A

  spring-server-A:
    image: spring-image
    container_name: spring-server-A
    ports:
      - "8001:8080"

  #server B
  spring-server-B:
    image: spring-image
    container_name: spring-server-B
    ports:
      - "8002:8080"

  #server C
  spring-server-C:
    image: spring-image
    container_name: spring-server-C
    ports:
      - "8003:8080"

  #server D
  spring-server-D:
    image: spring-image
    container_name: spring-server-D
    ports:
      - "8004:8080"