version: '3'
services:

  #mySql server
  mysql-server:
    image: mysql
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
  #minio server
  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    #    volumes:
    #      - ./storage:/data
    volumes:
      - D:\minio-storage:/data
    environment:
      MINIO_ROOT_USER: khue1234
      MINIO_ROOT_PASSWORD: khue1234
    command: server --console-address ":9001" /data

  #container A

  spring-server-A:
    image: spring-image
    container_name: service-A
    ports:
      - "8001:8080"

  #container B
  spring-server-B:
    image: spring-image
    container_name: service-B
    ports:
      - "8002:8080"

  #container C
  spring-server-C:
    image: spring-image
    container_name: service-C
    ports:
      - "8003:8080"

  #container D
  spring-server-D:
    image: spring-image
    container_name: service-D
    ports:
      - "8004:8080"


  #elastic-search
  elasticsearch:
    container_name: elastic-server
    image: elasticsearch:8.11.3
    networks:
      - elastic
    ports:
      - "9200:9200"

  #kibana
  kibana:
    container_name: kibana-server
    image: kibana
    networks:
      - elastic
    ports:
      - "5601:5601"

# config network

networks:
  elastic:
