#Database
DATABASE_URL: jdbc:h2:mem:mydb
DATABASE_USERNAME: sa
DATABASE_PASSWORD:
DATABASE_DRIVER: org.h2.Driver

#App

#Redis

#Token

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: songkhecole@gmail.com
EMAIL_PASSWORD: faet ytpt dlbc rjdh
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}

#Server
SERVER_PORT: 8080