#redis config
redis:
  host: localhost
  port: 6039
  password: root

#token config
app:
  jwtSecret: hello123
  jwtExpiration: 604800000
  jwtRefreshExpiration: 604800000
  jwtCookie: aaa
  jwtCookieName: app-jwt
  jwtRefreshCookieName: app-refresh-token

#data source
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: ${DATABASE_DRIVER}
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

server:
  port: ${SERVER_PORT:8080}
# redis config
#redis.host=localhost
#redis.port=6379
#redis.password=root

# token
#app.jwtSecret=khue123
#app.jwtExpiration=604800000
#app.jwtRefreshExpiration=604800000
#app.jwtCookie=aaaa
#app.jwtCookieName=app-jwt
#app.jwtRefreshCookieName=app-refresh-token

# enabled H2 console
#spring.h2.console.enabled=true

# config H2 database
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# jpa/hibernate
#server.servlet.session.timeout=60
#spring.jpa.hibernate.ddl-auto=update

#email
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=<login user to smtp server>
#spring.mail.password=<login password to smtp server>
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
