#Database
DATABASE_URL: jdbc:h2:mem:mydb
DATABASE_USERNAME: sa
DATABASE_PASSWORD:
DATABASE_DRIVER: org.h2.Driver

#App

#Redis

#Token

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: songkhecole@gmail.com
EMAIL_PASSWORD: oeeddxcmslcxjmwa

#Server
SERVER_PORT: 8080