#Database
DATABASE_URL: jdbc:h2:mem:mydb
DATABASE_USERNAME: sa
DATABASE_PASSWORD:
DATABASE_DRIVER: org.h2.Driver

#App

#Redis
REDIS_HOST: redis-17168.c252.ap-southeast-1-1.ec2.cloud.redislabs.com
REDIS_PORT: 17168
REDIS_PASSWORD: hz2lSDNa5sJHQJAlhuLSXxhqP8l1Cuvc
REDIS_USERNAME: default

#Token

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: songkhecole@gmail.com
EMAIL_PASSWORD: oeeddxcmslcxjmwa

#Server
SERVER_PORT: 8080